name: test_cd

on:
  push:
  pull_request:


jobs:
  ci:
    # Step 1. Set up operating system
    runs-on: ubuntu-latest
    steps:
    # Step 2. Set up Python 3.9
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    # Step 3. Check-out repository so we can access its contents
    - uses: actions/checkout@v2
    
    - name: Disable admin branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
        
          branch: main
          enforce_admins: false
